In [1]:
import pandas as pd
import numpy as np

# Json data cleaning: Scouting Reports 2019 - 2023

In [ ]:
# Read in the scouting report data for each year
recruits_2019 = pd.read_json(r'../Data/scouting_reports_2019.json')
recruits_2020 = pd.read_json(r'../Data/scouting_reports_2020.json')
recruits_2021 = pd.read_json(r'../Data/scouting_reports_2021.json')
recruits_2022 = pd.read_json(r'../Data/scouting_reports_2022.json')
recruits_2023 = pd.read_json(r'../Data/scouting_reports_2023.json')

### 2019 Data Cleaning
---

In [ ]:
# Take a peek at the 2019 data
recruits_2019.head()

,name,url,rank,position,height,weight,composite_rating,school_info,city,state,...,skill_delivery,skill_pocket_presence,skill_accuracy,skill_intangibles,skill_outside_the_pocket,skill_mobility,skill_arm_strength,skill_size,skill_playmaking_ability,skill_speed
0,Spencer Rattler,https://247sports.com/player/spencer-rattler-8...,1,PRO,6-1,198,99,"Pinnacle (Phoenix, AZ)",Phoenix,AZ,...,10.0,9.0,9.0,8.0,8.0,8.0,8.0,6.0,NaN,NaN
1,Jayden Daniels,https://247sports.com/player/jayden-daniels-89...,2,DUAL,6-3,175,97,"Cajon (San Bernardino, CA)",San Bernardino,CA,...,8.0,9.0,9.0,9.0,NaN,NaN,9.0,7.0,10.0,9.0
2,Bo Nix,https://247sports.com/player/bo-nix-77945/,3,DUAL,6-1.5,207,96,"Pinson Valley (Pinson, AL)",Pinson,AL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sam Howell,https://247sports.com/player/sam-howell-91707/,4,DUAL,6-0,225,95,"Sun Valley (Monroe, NC)",Monroe,NC,...,8.0,9.0,8.0,8.0,9.0,8.0,8.0,6.0,NaN,NaN
4,Max Duggan,https://247sports.com/player/max-duggan-87561/,5,DUAL,6-2,190,94,"Lewis Central (Council Bluffs, IA)",Council Bluffs,IA,...,9.0,9.0,9.0,10.0,NaN,NaN,8.0,8.0,9.0,10.0

Note: Specific issue with some players committed school being list as their high school instead of the college due to some of html code. Issue may be more prevlent for lower ranking players because they may not have commited anywhere out of high school, likely walk ons. Take a look at this below.

In [9]:
recruits_2019['committed_school'].value_counts()

committed_school
Arizona State Sun Devils    3
Alabama Crimson Tide        3
Ole Miss Rebels             3
Iowa State Cyclones         3
SMU Mustangs                3
                           ..
Northeast                   1
Norco                       1
Archbishop Moeller          1
Illinois State              1
Austin Peay                 1
Name: count, Length: 203, dtype: int64

List of mixed up schools
- N
- Oak Park
- Desert Mountain
- Fulton
- Charminade
- Cave Spring
- Wilsonville
- North Paudling
- Central Washington?
- JSerra Catholic
- Joe T. Robinson
- Reseda Senior
- Mountain Pointe
- Loveland
- Christian Academy of Knoxville
- Sherman
- Columbus North
- McArthur
- Oak Ridge
- Winslow Township
- Lumberton Senior
- Crosby
- Texas-Permian Basin
- Downey
- Lamar
- Puyallup 
- Pope John XXIII
- Crescent Valley
- Locust Grove
- Coppell
- Christ Presbyterian Academy
- Brooks College Prep
- Lutheran South
- Rainier Beach
- Patriot
- El Cerrito
- Bothell
- Prescott
- Royal
- Glacier Peak
- Warren
- Hardin Valley Academy
- Banks
- Trinity Episcopal
- Northeast
- Norco
- Archbishop Moeller


Seems like there are a ton of mix ups, espcially later in the data

In [10]:
recruits_2019[recruits_2019['committed_school'] == 'N']

,name,url,rank,position,height,weight,composite_rating,school_info,city,state,...,skill_delivery,skill_pocket_presence,skill_accuracy,skill_intangibles,skill_outside_the_pocket,skill_mobility,skill_arm_strength,skill_size,skill_playmaking_ability,skill_speed
19,Ty Evans,https://247sports.com/player/ty-evans-46038038/,23,PRO,6-2,192,89,"Palmer Ridge (Monument, CO)",Monument,CO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN